import React from 'react'
import Head from 'next/head'
import type { GetStaticProps, InferGetStaticPropsType } from 'next'
import { useTranslation, Trans } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import HeaderApp from '@/components/DownloadPage/HeaderApp'
import AboutPage from '@/components/DownloadPage/AboutPage'
import MetaData from '@/components/DownloadPage/MetaData'



type Props = {
}

const DownloadPage = (_Props: InferGetStaticPropsType<typeof getStaticProps>) =>  {
  //const router = useRouter()
 
   
  const { t } = useTranslation('download')
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="canonical" href={`${process.env.NEXT_PUBLIC_HOST}${t('canonical')}`} />
        <link rel="amphtml" href={`${process.env.NEXT_PUBLIC_HOST}${t('canonical')}/amp`} />
        <link rel="alternate" hrefLang="x-default" href={`${process.env.NEXT_PUBLIC_HOST}`} />
        <link rel="alternate" hrefLang="en" href={`${process.env.NEXT_PUBLIC_HOST}`} />     
        <link rel="alternate" hrefLang="hi" href={`${process.env.NEXT_PUBLIC_HOST}/hi`} />
      </Head> */}
      <MetaData />
      <HeaderApp/>
      <AboutPage/>
    </>
  )
}

// or getServerSideProps: GetServerSideProps<Props> = async ({ locale })
export const getStaticProps: GetStaticProps<Props> = async ({ locale }) => ({
  props: { 
    ...await serverSideTranslations (locale ?? 'en', ['download'])  ,
  },
})

export default DownloadPage

